### PR TITLE
Feature/jld protocols

### PR DESCRIPTION
**Pull request by zonotope**
@bplatz, @dpetran I've been working my way through the JSON-LD code since Friday and I have some changes I'd like to add that I think will make our Clojure code more idiomatic and simplify both the api and development process. 

Most of the changes here involve removing closure functions from abstract record types (`connection-storage-read`, for example). These functions encapsulate and hide their configuration, thus making them difficult to reason about at run time, at the repl, and in development. Instead, I think we should favor using record types to explicitly store their configuration (and only their configuration), and use the implemented protocol methods to define the behavior for these record types.

So, to make this concrete, instead of having an `IPFSConnection` record that has a `write` field that stores a closure defined with a [`default-commit-fn` here](https://github.com/fluree/db/blob/e1a39c57b0fec041d2403ac70d85c06ef0a57d57/src/fluree/db/method/ipfs/core.cljc#L12-L27) that returns a closure that encapsulates and hides an ipfs endpoint, and then use that closure to implement a protocol method, we should instead attach the configuration required (the ipfs endpoint in this case) to the record object and then either (1) implement the functionality of the closure in the protocol method directly and reference the configuration from the record fields, or (2) explicitly pass the ipfs endpoint configuration to a regular (non-closing) function. This approach is both more idiomatic and makes the debugging and development process much easier.

The other thing I did here is removed the `boolean` fields/methods like `transactor?` and `read-only?` from our record implementations and protocols. These booleans have been traditionally used for run time polymorphism and control flow (`(if (transactor? x) (do-transactor-thing) (do-non-transactor-thing))`) in our code bases. Clojure records and protocols were explicitly designed to flexibly and efficiently enable run time polymorphism, so I think it would be much more idiomatic for us to explicitly define new records and protocol implementations in the cases where these booleans are necessary. So, instead of one general `Connection` record with a `transactor?` or `read-only?` field/protocol method, we have a `TransactingConnection` and/or `ReadOnlyConnection` records as appropriate. That way, we can let the compiler handle control flow instead of relying on `if` blocks in our code which makes the code both slower and harder to reason about. 

The rest of the changes here are just minor cleanup. 

I have some more changes that I think will de-complect our indexer/ledger/db record implementations, but I think they will be a little more involved, so I will put them in another pr when I'm done with those.

### CODE REVIEW

**Review by dpetran — APPROVED** [review]
This looks good, and I especially like the idea of moving closures out. I'd be happy to see this in.

Do you mind opening up a draft PR that outlines some of the other protocol refactors you're working on? I've got some work on refactoring them as well and I'd like to see if it's compatible with yours.

**Review by bplatz — APPROVED** [review]
LGTM

**Comment by zonotope** [comment]
> Do you mind opening up a draft PR that outlines some of the other protocol refactors you're working on? I've got some work on refactoring them as well and I'd like to see if it's compatible with yours.

@dpetran to be honest, I'm still thinking through what I think the api should look like as I get more acquainted with the code and functionality we're going after, so I don't think I'm ready for even that step yet. I was working through my local js testing setup so I didn't get a chance to continue on this as much as I wanted. Apparently 16 gigs of RAM is not enough to run our js test suite :)

At a high level, I think the concepts of `Indexer`, `Ledger`, and `Db` are pretty intertwined right now, and I'd like to simplify them in the [Rich Hickey sense](https://www.infoq.com/presentations/Simple-Made-Easy/). 

I got this feeling from the `-new-indexer` method on the connection protocol. It seems to me like the connection shouldn't be concerned with instantiating a new indexer, and if it needs to interact with an indexer it should do it solely through the protocol, but removing that method started to affect lots of parts of the code, so I wanted to take a step back and think about the abstractions.

I don't think I have it figured out yet, but I _think_ we want to have a ledger that maintains a store of commits that build on each other, and an indexer that watches what the ledger produces and indexes it as necessary, and a db that is as close to flat, static data that is both queriable and directly tied to a commit as possible, but, again, I don't think I've settled on the right abstractions yet.

How were you thinking to refactor the protocols?

**Comment by zonotope** [comment]
It looks like the failures in CI also exist in the base `fluree/jld` branch as well, so they weren't introduced here. Wes is in the middle of merging `fluree/jld` with the current main branch so he can promote it to the new main, so I'll wait for him to finish that and merge this branch after he's done so as not to make that process more difficult.

**Comment by cap10morgan** [comment]
Re-targeted at `main` and good to merge whenever you're ready

**Pull request merged**
