### PR TITLE
Feature/fuel calculation

### PR DESCRIPTION
**Pull request by zonotope**
This patch adds a fuel tracker to the fql query stack consisting of an atom of volatiles used for tracking the number of flakes passing through the query processor. The atom contains a single volatile for each processing thread which uses a transducer to isolate the updates for each volatile, so there should be no contention within the individual volatiles. The atom updates should be limited to new index scans, which roughly correspond to the number of triples within each where clause. 

I have a few benchmarks of querying a ledger loaded with the schema.org vocabulary comparing different fuel tracker implementations: a noop which is just a `(map identity)` transducer, the proposed atom of volatiles, a single volatile, and a single atom. The numbers are frankly all over the place, so I'm not ready to draw any conclusions at this point, other than that this approach isn't disqualified because of performance. I will post the benchmark results in a comment below. 

This patch also has a few opportunistic changes like removing unused code related to legacy dbfunctions and the `-search` method on the db protocol. It also adds an uncached t-range resolver that is useful for benchmarking, and modifies the development logback.xml to make repl logs less noisy.

### CODE REVIEW

**Comment by zonotope** [comment]
I've done some benchmarks with different possible implementations to see the impact calculating fuel costs. I am querying a ledger loaded with the schema.org vocabulary. I have tried different queries which touch a varying number of flakes and which return varying numbers of results.

## Query 1
```clojure
'{:select [?s ?label]
  :where [[?person "id" "schema:Person"]
          [?s "schema:rangeIncludes" ?person]
          [?s "rdfs:label" ?label]]}
```
### Results

#### NoOp

Evaluation count : 13140 in 60 samples of 219 calls.
             Execution time mean : 4.798562 ms
    Execution time std-deviation : 133.869241 µs
   Execution time lower quantile : 4.535833 ms ( 2.5%)
   Execution time upper quantile : 5.026715 ms (97.5%)
                   Overhead used : 5.308349 ns

#### Atom of Volatiles

Evaluation count : 13860 in 60 samples of 231 calls.
             Execution time mean : 4.946484 ms
    Execution time std-deviation : 268.488812 µs
   Execution time lower quantile : 4.509169 ms ( 2.5%)
   Execution time upper quantile : 5.343955 ms (97.5%)
                   Overhead used : 5.234247 ns

Found 1 outliers in 60 samples (1.6667 %)
    low-severe	 1 (1.6667 %)
 Variance from outliers : 40.1321 % Variance is moderately inflated by outliers

#### Single Volatile

Evaluation count : 14580 in 60 samples of 243 calls.
             Execution time mean : 4.495154 ms
    Execution time std-deviation : 123.912183 µs
   Execution time lower quantile : 4.271094 ms ( 2.5%)
   Execution time upper quantile : 4.740224 ms (97.5%)
                   Overhead used : 5.247733 ns

#### Single Atom

Evaluation count : 13560 in 60 samples of 226 calls.
             Execution time mean : 4.825899 ms
    Execution time std-deviation : 233.887442 µs
   Execution time lower quantile : 4.477444 ms ( 2.5%)
   Execution time upper quantile : 5.184948 ms (97.5%)
                   Overhead used : 5.238332 ns

## Query 2
```clojure
'{:select-distinct [?s ?label]
  :where [[?person "id" "schema:Person"]
          [?s "schema:rangeIncludes" ?person]
          [?s "rdfs:label" ?label]
          [?s "schema:domainIncludes" ?domain]
          [?other "schema:domainIncludes" ?domain]
          [?other "rdfs:label" ?otherLabel]]}
```
### Results

#### NoOp

Evaluation count : 420 in 60 samples of 7 calls.
             Execution time mean : 169.330927 ms
    Execution time std-deviation : 5.700168 ms
   Execution time lower quantile : 160.945990 ms ( 2.5%)
   Execution time upper quantile : 180.628788 ms (97.5%)
                   Overhead used : 5.236718 ns

Found 1 outliers in 60 samples (1.6667 %)
    low-severe	 1 (1.6667 %)
 Variance from outliers : 20.5878 % Variance is moderately inflated by outliers

#### Atom of Volatiles

Evaluation count : 420 in 60 samples of 7 calls.
             Execution time mean : 164.381591 ms
    Execution time std-deviation : 7.929616 ms
   Execution time lower quantile : 153.651195 ms ( 2.5%)
   Execution time upper quantile : 180.682168 ms (97.5%)
                   Overhead used : 5.342538 ns

Found 1 outliers in 60 samples (1.6667 %)
    low-severe	 1 (1.6667 %)
 Variance from outliers : 33.6291 % Variance is moderately inflated by outliers

#### Single Volatile

Evaluation count : 420 in 60 samples of 7 calls.
             Execution time mean : 169.372631 ms
    Execution time std-deviation : 5.232452 ms
   Execution time lower quantile : 163.281788 ms ( 2.5%)
   Execution time upper quantile : 183.771744 ms (97.5%)
                   Overhead used : 5.236804 ns

Found 3 outliers in 60 samples (5.0000 %)
    low-severe	 3 (5.0000 %)
 Variance from outliers : 17.4162 % Variance is moderately inflated by outliers

#### Single Atom

Evaluation count : 420 in 60 samples of 7 calls.
             Execution time mean : 163.597953 ms
    Execution time std-deviation : 1.943606 ms
   Execution time lower quantile : 160.026065 ms ( 2.5%)
   Execution time upper quantile : 167.132291 ms (97.5%)
                   Overhead used : 5.250268 ns

**Comment by dpetran** [comment]
This looks good, here's my understanding:

The meat of it is in the new fuel namespace where you've got the new `track` transducer that increments a volatile for every flake that passes through during the `tree-chan` call. The tracker gets initialized as a vector of volatiles and gets threaded down through the query stack - including the "modify" syntax  for transactions, but not (yet?) the basic "insert".

I don't see where we do the tallying for the "modify" syntax route. In general it would be nice to see some tests that show what the tallied output should be.

Thanks for taking the time to clean up logging and dead code, and doing the benchmarking. If you don't mind checking in your benchmarks in the `dev` directory I wouldn't mind stealing that infrastructure : )

**Comment by zonotope** [comment]
> This looks good, here's my understanding:
> 
> The meat of it is in the new fuel namespace where you've got the new `track` transducer that increments a volatile for every flake that passes through during the `tree-chan` call. The tracker gets initialized as a vector of volatiles and gets threaded down through the query stack - including the "modify" syntax for transactions, but not (yet?) the basic "insert".
> 
> I don't see where we do the tallying for the "modify" syntax route. In general it would be nice to see some tests that show what the tallied output should be.
> 
> Thanks for taking the time to clean up logging and dead code, and doing the benchmarking. If you don't mind checking in your benchmarks in the `dev` directory I wouldn't mind stealing that infrastructure : )

I meant to focus on standard queries for this pr. I will add fuel tracking for transactions and query functions including select aggregates and bind functions in subsequent prs. The tallying for modification operations as well as the insert fuel tracking will come with the transaction fuel tracking. 

Also, because my focus was on benchmarking the performance impact, the fuel is only tallied for now, but nothing is done with the tallied result. We still need to change the api functions to account for returned fuel usage.

I have just loaded the schema.org vocabulary into a ledger and issued a few queries against it using the `bench` function from criterium that's required in the `user` namespace. I will add the schema.org vocabulary json file as a dev resource so we can use it for other things.

**Comment by zonotope** [comment]
> This looks good to me, thanks for all the cleanup!
> 
> Is the plan to add tests for the tallied result once we're actually surfacing those tallies via the api? And to leave #242 open until that (and the other follow-on work) is complete?

I have pushed a commit that returns the tallied result from the `fluree.db.api.query/query` function when the `:meta` option on the passed in query is set, much like we return execution time currently. I will add tests today for the tallied result and merge this afterwards, assuming no unforeseen issues.

I'll leave #242 open for now because I still need to add fuel tracking for transactions. I think it will be another relatively big change because I think I will have to tweak the transact call stack so that a fuel transducer will work there, and I would like to benchmark that change too, so I would prefer to do it in a different pr.

**Pull request merged**
