### PR TITLE
Feature/union query

### PR DESCRIPTION
**Pull request by bplatz**
This addresses issue #250 and adds support for union clauses within where statements.

The core cases are supported here, but there could usages of union statements that are not covered here and may require some revisiting.

See new test namespace for examples.

### CODE REVIEW

**Comment by cap10morgan** [comment]
@bplatz Just FYI: If you say something like "Fixes #250" or "closes #250" in your PR it will automatically close the issue when the PR is merged. I'm not sure what all the supported variants are, but I know those two work at least.

**Comment by cap10morgan** [comment]
Getting a strange error (`No such var: union`) from the linter in CI. Not sure if that's something it should be told to ignore or an actual issue.

**Comment by cap10morgan** [comment]
Looks like [this line](https://github.com/fluree/db/blob/594f0db701a176805eb972b7d3dc9d76228c9ee4/src/fluree/db/query/analytical.cljc#L831) is calling a fn that doesn't exist in the aliased namespace? I think that's what the linter is complaining about.

**Comment by mpoffald** [comment]
@cap10morgan The `analytical` ns was unused and got removed in https://github.com/fluree/db/pull/259, this branch just doesn't have that change. So we can safely ignore that I think

**Pull request merged**
