### PR TITLE
FC-1272 Package and deploy JS artifacts from this repo

### PR DESCRIPTION
**Pull request by cap10morgan**
This packages and deploys our JS artifacts directly from this repo, eliminating the need for the fluree/flureejs repo and manual copying files over there, etc.

`make deploy` will now deploy the CLJ(S) library to Clojars and all three JS libraries to npmjs.com.

Closes FC-1227

### CODE REVIEW

**Comment by cap10morgan** [comment]
Needs one more thing before reviewing. I'll update this comment when that's pushed.

**Review by ldw1007 — DISMISSED** [review]
lgtm

**Comment by cap10morgan** [comment]
Woof, sorry about all the junk commits in here. npm was creating tags and commits behind my back 😠. Say the word and I will squash them down to something less noisy.

Anyway, this is a pretty big change, and it definitely breaks things (but we already did that w/ the fn renaming, sooooo cool?).

This builds a single JS artifact that contains the browser, webworker, and nodejs files all in one. I removed the npmjs deploy code so we can try just pulling these straight from GitHub using version tags or commit SHAs (or branches too in dev).

I need to test this all out some more and then update the README w/ my findings, so not quite ready for review yet, but getting closer.

**Comment by cap10morgan** [comment]
I tested this in the fluree-nodejs-server project and it worked there. Need to test in some browser scenarios too.

**Comment by dpetran** [comment]
When we make changes to non-cljs files will we have to regenerate the artifacts? Maybe we should have a pre-commit hook that runs the code generation step? I worry that the source and the artifacts will drift out-of-sync occasionally if we don't.

**Comment by cap10morgan** [comment]
@dpetran What non-cljs files are you thinking of? The general idea is that we try to keep everything we can in the CLJS source and generate the artifacts from that. But yes, any changes to files in the artifacts' build pipelines (cljs files first and foremost) will require regenerating the artifacts. But that was true before too. The only difference here is that the artifacts are committed to the same repo instead of a different one (and that is really only done to facilitate using GitHub URLs in consuming package.json files).

So I don't think this change in and of itself necessitates additional automation around artifact generation, but additional automation might have been and still be welcome nonetheless. I do think it's just enough outside the scope of this (already bigger than I'd hoped) PR to warrant its own separate one. But let me know if you disagree. :)

**Comment by dpetran** [comment]
> What non-cljs files are you thinking of?
Any of them, really. 

I think we're fine without making additional changes here, I was just thinking about the practical consequences of keeping artifacts in source control. So I guess it boils down to a policy question: should we just update the artifacts when we want to create a new release, or update them every time we make a change? or something in between

**Comment by cap10morgan** [comment]
@dpetran The reason I asked which files is that we shouldn't directly change generated JS files, and there aren't too many other non-cljs files. But even changes to the cljs files necessitate rebuilding the artifacts. So I just wanted to make sure I understood your concern.

I think it would make sense to automate artifact generation at some point (soon?) to ensure they are in sync with the rest of the source at any given commit. Having them in the same repo does imply a bit more of a contract there. Perhaps a pre-commit hook and/or a GitHub Action that fails if they aren't in sync? At least the latter, IMO.

**Comment by dpetran** [comment]
Sorry, when I said "any of them" I was thinking of the cljc files in the main `src/` directory, I didn't even think of the js files. 

So, I understand that the policy should be "update on every commit", then, right? We can do that manually until we get automation, I just wanted to be clear what the expectation going forwards will be.

**Comment by cap10morgan** [comment]
"Policy" might be a strong word for it. It's just my opinion, and it sounds like yours too. But yeah, if I came across a GitHub repo w/ artifacts in it, I would hope and expect that those artifacts reflected the code, config, etc. at that same commit and not some arbitrarily older one. So sure, let's make it a policy! 😤

**Comment by cap10morgan** [comment]
After researching things a bit, I think given that we are breaking backwards compatibility here anyway (new fn names), the best approach would be to package the now-unified JS artifact as an ES module (the new standard that works in both Node 12+ and all modern browsers) and name it `@fluree/db` for consistency with the repo name. I need to play around with it out a bit more, but it looks like that should allow simple usage of all three entrypoints (i.e. browser, web-worker, & node) from the same artifact.

**Comment by bplatz** [comment]
> After researching things a bit, I think given that we are breaking backwards compatibility here anyway (new fn names), the best approach would be to package the now-unified JS artifact as an ES module (the new standard that works in both Node 12+ and all modern browsers) and name it `@fluree/db` for consistency with the repo name. I need to play around with it a bit more, but it looks like that should allow simple usage of all three entrypoints (i.e. browser, web-worker, & node) from the same artifact.

That sounds great. I assume the 3 artifacts are independent builds (i.e. file sizes, related to bundled capability). I suppose if they weren't there would just be one entrypoint, but just want to make sure.

**Comment by cap10morgan** [comment]
@bplatz Yes, still three independent builds. The layout inside the JS package looks like this:

```
/package.json
/js
    /browser
        /index.js
    /webworker
        /index.js
    /nodejs
        /index.js
```

...and then in the `package.json` file I can tell it to use `js/nodejs/index.js` as the main when running on node, `js/browser/index.js` when running on a browser, and to also expose a `@fluree/db/webworker` import that brings in `js/webworker/index.js` when you want to pull that in.

**Pull request closed without merging**
