### PR TITLE
Include IRIs in `values` bindings

### LINKED ISSUE #703: Allow `values` to include subject IRIs
If a query specifies compacted IRIs in a `values` clause, they are not expanded.

```clojure
{"@context" context
  "values" ["?s" ["ex:2914cb3a-d6a8-4978-8df2-a5919bee3054" "ex:5b673c38-aa12-4512-aee7-8fd7145c79c6"]]
  "where" {"@id" "?s" "?p" "?o"}
   "select" ["?s" "?p" "?o"]}

;; parses to

{:context {:type-key "@type", "ex" {:id "http://example.org/"}, "schema" {:id "http://schema.org/"}, "f" {:id "https://ns.flur.ee/ledger#"}},
   ;; values aren't expanded, datatype is string
   :values [{?s #:fluree.db.query.exec.where{:var ?s, :val "ex:2914cb3a-d6a8-4978-8df2-a5919bee3054", :datatype 1}}
            {?s #:fluree.db.query.exec.where{:var ?s, :val "ex:5b673c38-aa12-4512-aee7-8fd7145c79c6", :datatype 1}}],
   :where
   #:fluree.db.query.exec.where{:patterns
                                ([#:fluree.db.query.exec.where{:var ?s}
                                  #:fluree.db.query.exec.where{:var ?p}
                                  #:fluree.db.query.exec.where{:var ?o}])},
   :select [#fluree.db.query.exec.select.VariableSelector{:var ?s}
            #fluree.db.query.exec.select.VariableSelector{:var ?p}
            #fluree.db.query.exec.select.VariableSelector{:var ?o}],
   :opts {}}
```

### PR DESCRIPTION
**Pull request by zonotope**
Fixes #703 by adding syntax to specify the data type of a values binding using an `@value` map that also contains an `@type` key. when the value of `@type` is `"xsd:anyURI"`, then the value of the `@value` key is treated as an iri and expanded.

### CODE REVIEW

**Comment by aaj3f** [comment]
@zonotope so to clarify, would this be correct:
```json
{
  "@context": {
    "ex": "http://example.org/",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "where": {
    "@id": "?s",
    "name": "Andrew"
  },
  "delete": {
    "@id": "?s",
    "name": "Andrew"
  },
  "insert": {
    "@id": "?s",
    "name": "Andrew Johnson"
  },
  "values": [
    ["?s", [{ "@value": "ex:andrew", "@type": "xsd:anyURI" }] ]
  ],
}
```

**Comment by zonotope** [comment]
> @zonotope so to clarify, would this be correct:
> 
> ```json
> {
>   "@context": {
>     "ex": "http://example.org/",
>     "xsd": "http://www.w3.org/2001/XMLSchema#"
>   },
>   "where": {
>     "@id": "?s",
>     "name": "Andrew"
>   },
>   "delete": {
>     "@id": "?s",
>     "name": "Andrew"
>   },
>   "insert": {
>     "@id": "?s",
>     "name": "Andrew Johnson"
>   },
>   "values": [
>     ["?s", [{ "@value": "ex:andrew", "@type": "xsd:anyURI" }] ]
>   ],
> }
> ```

Yes it would, but I should also add a test to make sure insert/delete/where with iri values works as it should.

**Review by dpetran — APPROVED** [review]
:+1:

**Comment by zonotope** [comment]
@aaj3f I just added [a test using these values bindings in transactions](https://github.com/fluree/db/pull/754/commits/7a9371ef9dd679967521d45ead696f24c9147a0f)

**Comment by zonotope** [comment]
> @zonotope welcome to source code, President Fillmore and President Hayes!

I feel a little bad that Chester A. Arthur was left out though :(

**Pull request merged**
