### PR TITLE
Experiment/flexible components

### PR DESCRIPTION
**Pull request by dpetran**
This is the basic shell of refactoring into discrete, composable components. It works, and it has tests. Here's what's missing that our current implementation has:
- loading an existing ledger
- cljs support
- ipfs store

It should be 100% compatible with existing fluree, I've made sure not to make any changes to existing source code. There are efficiencies to be gained by doing that if we like this api, though.

Here's the design philosophy of the different components:

 Store
The store is only concerned with persisting and reading data.

Transactor
The transactor is only concerned with writing the commit log and reading/verifying it back if necessary. If we add consensus, this is where it would be applied.

Indexer
The indexer is only concerned with indexing transactions and fielding queries. It is completely ignorant of "ledgers" and only works with dbs - the indexed tuples.

Publisher
The publisher is the root of the name server. Its only job is to keep track of the ledger - the latest commit and the latest db.

### CODE REVIEW

**Comment by zonotope** [comment]
Here's my proposal for namespace naming. My assumptions are (and what I would prefer) that we have protocols that we adhere to for all of our top-level interacting components, and the "connection" object should use those protocols to orchestrate the overall public api. Each protocol is defined in a namespace named after the component (with one exception). That namespace should contain the protocol definition itself, and any functions wrapping that protocol definition intended for other parts of the codebase to call. This namespace will then serve as the "public" api for that particular component. The specific protocol implementations should live in different namespaces under the directory structure, and should only contain code specifically for implementing the protocol for that component.

For example, the indexer protocol should live in `fluree.db.indexer`. That namespace will contain at the top a `defprotocol` call defining the `Indexer` protocol with a number of methods, and then function definitions wrapping those protocol methods that implement the common functionality that all indexers share. These functions should be what all other outside code uses to deal with indexers. Then, we have a `fluree.db.indexer.flake` namespace that only contains support functions necessary to implement the `Indexer` protocol for this specific indexer, and then a `defrecord` call to implement the `FlakeIndexer` record, calling those support functions defined in the same namespace. The same goes for `fluree.db.indexer.full-text`, etc.

We would follow a similar pattern for storage (`fluree.db.storage`, `fluree.db.storage.file`, `fluree.db.storage.s3`, ...)

Then, the one exception to this rule is the "top level" namespace, which would be `fluree.db`, and that would contain all the code that ties everything together along with the "connection" object, which does *not* need to be a protocol because there will be only one fluree connection that uses different combination of components depending on how it's deployed. It shouldn't matter to the connection whether it's writing to file storage or s3, or what, or how many, indexers it uses. We should have a function that creates a connection, and you pass that function whatever protocol implementations you want.

I don't think there's any need for "public"/"private" code besides protocols and functions using protocols. Enforcing the type of modularity we're going for is one of the main design goals of protocols, so I think we should make sure we're using the built in facilities of the language effectively before we introduce more structure.

**Comment by zonotope** [comment]
Are there any objections to closing this pull request?

**Comment by dpetran** [comment]
I'd like to do a proper review. It implements a lot of functionality that is on the roadmap and could be valuable. The code reflects the architectural goals that we've been discussing at the architecture meetings. 

- working fluree server, including subscriptions and broadcast
- working name service implementation
- working transaction persistence, good foundation for consensus implementation
- uses db as an immutable value, no mutation
- good foundation for query server
- good foundation for nexus architecture
- all with comprehensive tests and documented code
- good foundation for Wes' fractal architecture idea
- rebases cleanly on top of current main branch

**Comment by zonotope** [comment]
We have near term priorities that we have identified are more important to work on right now than any of the items you've mentioned. Reviewing a patch with 55 files modified and 3k lines of code added is a distraction from those priorities.

Even if we were to review this patch right now, we don't have enough information to judge these changes for the purported benefits you list. Those items you mentioned are _later_ in the roadmap for a reason. Neither you nor anyone else can know that any of the items you've listed are actually "working", because we don't have enough information to nail down all the things these items are supposed to do, or which particular abstraction fits the real world problems users of the database need to solve. 

We will refine the architecture and requirements for each of these components as we refine our understanding of the use cases. I don't think it's worthwhile to commit to changing the architecture of the entire code base all at once without the necessary context.  

We will build each of these components as we need them to solve problems our users have and when we understand the context constraining those problems. Please contribute the relevant ideas from this patch to the implementation discussion at that time. 

> It implements a lot of functionality that is on the roadmap and could be valuable. The code reflects the architectural goals that we've been discussing at the architecture meetings.
> 
>     * working fluree server, including subscriptions and broadcast
> 
>     * working name service implementation
> 
>     * working transaction persistence, good foundation for consensus implementation
> 
>     * uses db as an immutable value, no mutation
> 
>     * good foundation for query server
> 
>     * good foundation for nexus architecture
> 
>     * all with comprehensive tests and documented code
> 
>     * good foundation for Wes' fractal architecture idea
> 
>     * rebases cleanly on top of current main branch

**Pull request closed without merging**
