### PR TITLE
Add credential? & verifiable-credential? pred fns

### PR DESCRIPTION
**Pull request by cap10morgan**

### CODE REVIEW

**Comment by cap10morgan** [comment]
* **#841** <a href="https://app.graphite.dev/github/pr/fluree/db/841?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @cap10morgan and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by dpetran — APPROVED** [review]
This looks good, but it reminds me of a niggle I have:

The "credential-" naming convention already feels a bit legacy, since we support non-credential means of authentication. And we may support more types in the future.

It feels like we should have a more general naming convention but for we rush this out:
- protected-
- authorized-
- closed-
- some-other-name?

**Comment by cap10morgan** [comment]
> This looks good, but it reminds me of a niggle I have:
> 
> 
> 
> The "credential-" naming convention already feels a bit legacy, since we support non-credential means of authentication. And we may support more types in the future.
> 
> 
> 
> It feels like we should have a more general naming convention but for we rush this out:
> 
> - protected-
> 
> - authorized-
> 
> - closed-
> 
> - some-other-name?

I'm not opposed to any of that, but it does feel out of scope for this PR

**Comment by dpetran** [comment]
Oh definitely, this PR just reminded me of it.

**Pull request merged**
