### PR TITLE
Do not subtract retracts from db :size

### PR DESCRIPTION
**Pull request by JaceRockman**
This is a fix for https://github.com/fluree/db/issues/351

### CODE REVIEW

**Comment by zonotope** [comment]
@JaceRockman the tests fail on this branch. Do you still want to keep this pull request open?

**Comment by JaceRockman** [comment]
> Hi @JaceRockman I think this might not be `false` `.-op` (retraction) flakes, but flakes that are completely removed during staging.
> 
> Therefore I think the counts are accurate.
> 
> For context, note this is the main place this is called when transacting:
> 
> https://github.com/fluree/db/blob/2a9db1b669784b3897c99b8ace5980c7acc6b869/src/clj/fluree/db/json_ld/transact.cljc#L188
> 
> And for the function as a whole, on line 181:
> 
> https://github.com/fluree/db/blob/2a9db1b669784b3897c99b8ace5980c7acc6b869/src/clj/fluree/db/json_ld/transact.cljc#L177-L191
> 
> That `remove` is only ever used for stage operations (in-between commits). This means that `add` actually has both addition and retraction flakes in it (probably could have used a better name).
> 
> The main thing is `remove` is different than `retract`, and therefore the counts looks like they were accurate.

@bplatz So is issue https://github.com/fluree/db/issues/351 not actually a problem then? Or do you think it was fixed by some other change?

**Comment by bplatz** [comment]
@JaceRockman I'm not sure if that is still a problem... but if so I don't think this is the source.

The ticket says:

> fluree.db.json-ld.transact/final-db calculates the size of the asserts and subtracts the size of the retracts

But I *think* this is incorrect... it subtracts the size of `remove`, not `retract` (what I think was meant by "subtracts" above)... and `remove` is only ever used with multiple `fluree/stage` calls in-between commits. I think our naming here is confusing, because in `final-db` what it calls `add` is actually both assertions + retractions.

If this is still a problem, my best guess is that when we reify, we include commit metadata flakes when calculating size, but when transacting we don't include the commit metadata flakes. But that is just a guess.

**Comment by JaceRockman** [comment]
@cap10morgan @bplatz I ran the tests in this branch https://github.com/fluree/db/tree/fix/inconsistent-db-stats on the most recent version of main and they passed with flying colors, so I think the original issue got fixed over the course of some other changes. I wanted to check with you before closing just to be sure though.

**Comment by cap10morgan** [comment]
> @cap10morgan @bplatz I ran the tests in this branch https://github.com/fluree/db/tree/fix/inconsistent-db-stats on the most recent version of main and they passed with flying colors, so I think the original issue got fixed over the course of some other changes. I wanted to check with you before closing just to be sure though.

I would say it's safe to close then. If we discover it should be re-opened later we can do that.

**Pull request closed without merging**
