### PR TITLE
Feature/jld select iri resolution

### PR DESCRIPTION
**Pull request by bplatz**
This is a significant change to compound queries in that it now passes both .-o values and datatypes as two-tuples.

Datatype is needed for some downstream operations (e.g. changing a subject integer ID into an IRI in `select` output). Other operations also need to verify they are working with same-type data, since mixed types can be present for any predicate - e.g. a 'max' function can only operate on numbers, or an object that is an IRI, like :ex/friend's value, can only be passed into the subject of the subsequent where statement if the value is actually an IRI.. so if any other datatypes exist for that value it must be filtered out.

Now that some two-tuple values are being passed through where, grouping, and select statements - it must be tracked so the operations receiving the values know if it is getting a two-tuples. This could be done by checking every incoming value to see if it is a two-tuple but that would be very inefficient if we can know this up-front.

As a result of this change, an example of how output changes is this query:
```
@(fluree/query db
                 {:select ['?s '?p '?o]
                  :where  [['?s :schema/age 34]
                                 ['?s '?p '?o]]})
```
Now correctly outputs:
```
[[:ex/cam :id "http://example.org/ns/cam"]
 [:ex/cam :rdf/type :ex/User]
 [:ex/cam :schema/email "cam@example.org"]
 [:ex/cam :schema/age 34]
 [:ex/cam :ex/favNums 5]
 [:ex/cam :ex/favNums 10]
 [:ex/cam :ex/friend :ex/brian]
 [:ex/cam :ex/friend :ex/alice]]
```
whereas prior to this PR, the output would have integer ids for all ?s and ?p values, and the ?o values that are IRIs (the last two in the above results) would also be the integer ID.

### CODE REVIEW

**Comment by cap10morgan** [comment]
If possible let's retarget this at the main branch once I finish merging the existing feature/jld into it. Should hopefully not be too long. I'll post an update in here when it's done.

**Review by zonotope — APPROVED** [review]
🔢

**Comment by cap10morgan** [comment]
In case my earlier comment didn’t make it clear, please don’t merge this into either branch just yet. Thank you!

**Comment by cap10morgan** [comment]
Re-targeted at `main` and good to merge whenever you're ready

**Pull request merged**
