### PR TITLE
Feature/having

### LINKED ISSUE #313: Implement HAVING for FlureeQL
Add having clauses like those described in the [SPARQL Spec](https://www.w3.org/TR/sparql11-query/#having) to FlureeQL

~Blocked by #304~

### PR DESCRIPTION
**Pull request by zonotope**
Implements `:having` clauses by creating an `eval` namespace that compiles user-supplied code into clojure functions after validating that it only references a pre-specified list of functions. 

I think we should convert the aggregate and filter processing code to use the eval namespace because it is both more flexible and general, but those changes will come in another pull request (probably the one for #272). 

Closes #313

### CODE REVIEW

**Comment by mpoffald** [comment]
> I think we should convert the aggregate and filter processing code to use the eval namespace because it is both more flexible and general

I support this idea. This would obviate the `analytical-filter` ns entirely, right? Looks like what you have here duplicates most of it, so we could just get rid of it after porting filters over

**Comment by zonotope** [comment]
> > I think we should convert the aggregate and filter processing code to use the eval namespace because it is both more flexible and general
> 
> I support this idea. This would obviate the `analytical-filter` ns entirely, right? Looks like what you have here duplicates most of it, so we could just get rid of it after porting filters over

Yes, the `eval` ns should eventually replace both the analytical_filter and the parse/aggregate namespaces.

**Comment by cap10morgan** [comment]
Ohhh... I think I'm going to rebase my local `feature/query-bind` around this.

**Comment by zonotope** [comment]
> Ohhh... I think I'm going to rebase my local `feature/query-bind` around this.

Yeah, the `eval/compile` function will probably prove quite useful :)

**Pull request merged**
