### PR TITLE
Feature: S3 connection method

### LINKED ISSUE #450: Implement S3 connection
It is highly likely we'll use S3 at least initially for Nexus, and regardless others will want it.

Some notes:
- `commit!` has a persistence guarantee, so we'll need to block before commit! returns until confirmation of a successful write. Depending on library's async APIs, this might impact how it is implemented.
- S3 writes are likely enough to fail we'll need at least some minimal retry logic and then exception reporting. IPFS likely has similar (or higher) failure rate, so ideally the same exception capturing can be used for both (as well as file conn), but if not we should create a ticket for IPFS failure/retry as to not delay having the base S3 support.
- While writing the 2 files needed for a commit (or 3, if there is a new defaultContext), it can (and should) happen in parallel as the i/o will be the bottleneck for speed. Unfortunately for IPFS we won't know the file addresses until we write, so at least IPFS must remain serial. Also, this parallelization will require a cleanup function if some writes succeed and others fail. For now we should just keep it serial, and address a parallel option in a different ticket.
- fluree/ledger has a good clean S3 library and set of base fns that hopefully can mostly get reused.
- Not sure if this can work with CLJS, if not straight forward we should make this CLJ-only and throw an exception from CLJS if someone tries to create an S3 conn. We can add a CLJS-specific ticket and address its priority independently.
- There is increasingly a number of the same/similar functions in the different conn type namespaces. It would be great to chip away at this a little bit, but anything that takes a large effort ideally should exist as its own ticket so it can get best prioritized against the other tickets.

### PR DESCRIPTION
**Pull request by cap10morgan**
Closes #450 

Commit 7efcd2f87ccfff45b636d6d57637ae215bd7768d is the heart of this PR.

No tests yet b/c testing S3 is a little tricky. If folks feel strongly there should be some before merging I can figure out a good way to test this locally w/o actually connecting to S3.

It works in my REPL, though! ;)

### CODE REVIEW

**Comment by cap10morgan** [comment]
Converted to draft b/c I remembered there's one thing I still need to finish in here. Will ping when it's ready for full review.

**Comment by cap10morgan** [comment]
The last commit (https://github.com/fluree/db/pull/464/commits/971dab858b15480994854b514e508dab57d836a5) is unrelated and I'm happy to split it out into its own PR if desired. But I ran into a common test failure here in one of our `load` tests where the loaded ledger's `t` is lower than the one we were building up in memory. I added a new test-utils fn that tries to keep loading until we get a ledger w/ a db `t` of at least that value. So hopefully that will make those tests more reliable.

**Comment by cap10morgan** [comment]
OK @fluree/core this is ready for review

**Review by zonotope — APPROVED** [review]
🪣

**Comment by bplatz** [comment]
> failure here in one of our `load` tests where the loaded ledger's `t` is lower than the one we were building up in memory

If this is after a `fluree/commit!` which is deref'd then this is a bug that should be high priority and get a new ticket. There should never be a return from commit! until persistence is guaranteed. Perhaps this is specific to a testing tool... not sure, but please advise.

**Comment by cap10morgan** [comment]
> > failure here in one of our `load` tests where the loaded ledger's `t` is lower than the one we were building up in memory
> 
> If this is after a `fluree/commit!` which is deref'd then this is a bug that should be high priority and get a new ticket. There should never be a return from commit! until persistence is guaranteed. Perhaps this is specific to a testing tool... not sure, but please advise.

Just to make sure I'm understanding things correctly:

This is a (deref'd) `commit!` followed by a `load`. If I understand things correctly, the `load` will use the latest pushed head commit when it is called, but [`push` is async](https://github.com/fluree/db/blob/fe486cd17fbbdbacdda3cc379b3f5bd77cb50406/src/fluree/db/json_ld/commit.cljc#L304-L309). So in these quick `commit!` then `load` scenarios in tests, it's possible to load before the push is complete. Does that seem right / expected?

**Comment by bplatz** [comment]
That's OK then... as the name service is intentionally async. We discussed creating an option for name services that could allow ones that can more easily support it to be synchronous and block... but e.g. IPNS as a name service really needs to be async.

However, the return from `commit!` should be a new db address... in this case there is no need to use the name service, as the only thing it does is tell us the db address that we should already know with the returned db.

I'd suggest any tests with this sort of dependency opt to not use the name service unless there is something specific about the name service itself they are testing.

**Pull request merged**
